apiVersion: kubeaddons.mesosphere.io/v1alpha1
kind: Addon
metadata:
  name: gatekeeper
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: gatekeeper
  annotations:
    appversion.kubeaddons.mesosphere.io/gatekeeper: "3.0.4-beta.1"
    docs.kubeaddons.mesosphere.io/gatekeeper: "https://github.com/open-policy-agent/gatekeeper/blob/master/README.md"
    values.chart.helm.kubeaddons.mesosphere.io/gatekeeper: "https://raw.githubusercontent.com/mesosphere/charts/master/staging/gatekeeper/values.yaml"
spec:
  kubernetes:
    minSupportedVersion: v1.15.0
  cloudProvider:
    - name: aws
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true
  chartReference:
    chart: gatekeeper
    repo: https://mesosphere.github.io/charts/staging
    version: 0.1.0
    values: |
      ---
      image:
        tag: v3.0.4-beta.1
      resources:
        limits:
          cpu: 1000m
          memory: 500Mi
        requests:
          cpu: 200m
          memory: 300Mi

