---
apiVersion: kubeaddons.mesosphere.io/v1alpha1
kind: Addon
metadata:
  name: kommander
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: kommander
  annotations:
    appversion.kubeaddons.mesosphere.io/kommander: "1.50.0"
    endpoint.kubeaddons.mesosphere.io/kommander: /ops/portal/kommander
spec:
  namespace: kommander
  kubernetes:
    minSupportedVersion: v1.15.0
  cloudProvider:
    - name: aws
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true
  chartReference:
    chart: kommander
    repo: https://gracedo.github.io/charts/stable
    version: 0.1.24
    values: |
      ---
      grafana:
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: ThanosQuery
              type: prometheus
              url: http://kommander-kubeaddons-thanos-query-http:10902/
              access: proxy
              isDefault: true
      thanos:
        query:
          stores:
            - "prometheus-kubeaddons-prom-prometheus.kubeaddons:10901"
            - "a749d33f342104bd08acfebd723f4e59-1454596863.us-west-2.elb.amazonaws.com:10901"
      karma:
        enabled: true
        configMap:
          rawConfig:
            alertmanager:
              interval: 30s
              servers:
                - name: kommander
                  uri: http://prometheus-kubeaddons-prom-alertmanager.kubeaddons:9093/
                  timeout: 10s
                  tls:
                    insecureSkipVerify: true
                - name: konvoy
                  uri: https://a61ae4f7008fd494dafc0354bdff1d32-2055828688.us-west-2.elb.amazonaws.com/konvoy/alertmanager
                  timeout: 10s
                  tls:
                    insecureSkipVerify: true
  requires:
    matchLabels:
      kubeaddons.mesosphere.io/provides: defaultstorageclass
