---
apiVersion: kubeaddons.mesosphere.io/v1alpha1
kind: Addon
metadata:
  name: localpathprovisioner
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: localpathprovisioner
    kubeaddons.mesosphere.io/provides: storageclass
  annotations:
    appversion.kubeaddons.mesosphere.io/localpathprovisioner: "1.0"
spec:
  kubernetes:
    minSupportedVersion: v1.14.0
  cloudProvider:
    - name: none
      enabled: true
  chartReference:
    chart: localpathprovisioner
    repo: https://mesosphere.github.io/charts/stable
    version: 0.1.0
