apiVersion: kubeaddons.mesosphere.io/v1alpha1
kind: Addon
metadata:
  name: traefik-forward-auth
  namespace: kubeaddons
spec:
  kubernetes:
    minSupportedVersion: v1.15.0
  requires:
    matchLabels:
      kubeaddons.mesosphere.io/name: dex
      values.chart.helm.kubeaddons.mesosphere.io/traefik-forward-auth: "https://raw.githubusercontent.com/mesosphere/charts/6c43b8ab10108fb1adba5c6dd10e800e5f1abdd0/staging/traefik-forward-auth/values.yaml"
  chartReference:
    chart: traefik-forward-auth
    repo: https://mesosphere.github.io/charts/staging
    version: 0.2.2
    values: |
      ---
      replicaCount: 1
      image:
        repository: mesosphere/traefik-forward-auth
        tag: 1.0.2
        pullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
      service:
        type: ClusterIP
        port: 4181
      traefikForwardAuth:
        # oidcUri will be overridden by the init-container
        oidcUri: "https://dex-kubeaddons.kubeaddons.svc.cluster.local:8080/dex"
        clientId: traefik-forward-auth
        clientSecret:
          valueFrom:
            secretKeyRef:
              name: dex-client-secret-traefik-forward-auth
              key: client_secret
        cookieSecure: true
        userCookieName: "konvoy_profile_name"
        allowedUser:
          valueFrom:
            secretKeyRef:
              name: ops-portal-credentials
              key: username
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
          ingress.kubernetes.io/protocol: https
          traefik.ingress.kubernetes.io/auth-type: forward
          traefik.ingress.kubernetes.io/auth-url: http://traefik-forward-auth-kubeaddons.kubeaddons.svc.cluster.local:4181/
        paths:
          - /_oauth
        hosts:
          - ""
        tls: []
      TODO: re-enable once we've got opsportal related secret issues worked out
      initContainers:
      # initialize-traefik-forward-auth deploys credentials for use by the proxy
      - name: initialize-traefik-forward-auth
        image: timaa2k/kubeaddons-addon-initializer:v0.0.8
        args: ["traefikforwardauth"]
        env:
        - name: "TFA_CONFIGMAP_NAME"
          value: "traefik-forward-auth-kubeaddons-configmap"
        - name: "TFA_NAMESPACE"
          value: "kubeaddons"
        - name: "TFA_INGRESS_NAMESPACE"
          value: "kubeaddons"
        - name: "TFA_INGRESS_SERVICE_NAME"
          value: "traefik-kubeaddons"
